development:
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST: 127.0.0.1
      PORT: 5432
      USER: postgres
      PASSWORD: postgres
      NAME: postgres
      
production:
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: challenge
      NAME: challenge